import React from "react";

const languages = [["Telugu","Original","341.48"],["Hindi","Dubbed","812.14"],["Tamil","Dubbed","58.56"],["Kannada","Dubbed","7.77"],["Malayalam","Dubbed","14.15"]];
const days = [294,155,172,208,93,80,69,55,67,103];
const territoryOpening = [["Andhra Pradesh","—","117.90"],["Telangana","—","149.70"],["AP + Telangana","—","320.80"],["Karnataka","20","23.70"],["Tamil Nadu","9.32","11.00"],["Kerala","5.38","6.35"],["Rest of India","72","86.00"],["India Total","192 Cr net","226 Cr gross"]];
const overseas = [["USA / Canada","128.80","66.35"],["UK / Ireland","20.40","8.15"],["Australia / New Zealand","28.90","11.55"],["UAE / GCC","46.60","18.65"],["Malaysia / Singapore","9.40","3.75"],["Rest of World","26.05","10.40"],["Overseas Total","260.15","118.85"]];
const dayRows = [
["Day 01","164.25","196.40","—","—","164.25 Cr net"],["Day 02","93.80","112.10","—","—","258.05 Cr net"],["Day 03","119.25","142.60","—","—","377.30 Cr net"],["Day 04","141.05","168.60","—","—","518.35 Cr net"],["Day 05","64.45","76.80","—","—","582.80 Cr net"],["Day 06","51.55","62.10","—","—","634.35 Cr net"],["Day 07","43.35","51.90","—","—","677.70 Cr net"],["Day 08","37.45","44.15","—","—","715.15 Cr net"],["Day 09","36.40","43.40","—","—","751.55 Cr net"],["Day 10","63.30","75.45","210.00","1,194.91","825.50 Cr net"]];

const Money=({children}:{children:React.ReactNode})=><span>{children} <small>Cr</small></span>;
const Table=({headers,rows}:{headers:string[],rows:string[][]})=><div className="tableWrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((x,j)=><td className={j===0?'name':''} key={j}>{x}</td>)}</tr>)}</tbody></table></div>;
const Section=({num,kicker,title,children,id}:{num:string,kicker:string,title:string,children:React.ReactNode,id?:string})=><section id={id} className="section"><div className="sectionHead"><div><div className="kicker">{kicker}</div><h2>{title}</h2></div><div className="sectionNo">{num}</div></div>{children}</section>;

export default function Page(){
 return <div className="page">
  <style>{`
@import url('https://fonts.googleapis.com/css2?family=Bebas+Neue&family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:wght@600;700;800;900&display=swap');
:root{--bg:#08090a;--panel:#101214;--panel2:#0c0e10;--text:#f1eee7;--muted:#858178;--dim:#55534e;--gold:#d4a85c;--gold2:#f0ce8b;--red:#a83b27;--line:#242628}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--bg)}.page{min-height:100vh;background:radial-gradient(circle at 50% -10%,#2b2115 0,transparent 28%),var(--bg);color:var(--text);font-family:'DM Sans',sans-serif}.page:before{content:"";position:fixed;inset:0;pointer-events:none;opacity:.035;background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='180' height='180'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.8' numOctaves='3'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E")}
.nav{position:sticky;top:0;z-index:10;height:64px;border-bottom:1px solid var(--line);background:rgba(8,9,10,.84);backdrop-filter:blur(18px)}.navInner{width:min(1240px,calc(100% - 48px));height:100%;margin:auto;display:flex;align-items:center;justify-content:space-between}.brand{display:flex;align-items:center;gap:10px;font-size:10px;letter-spacing:.22em;font-weight:700}.brandMark{width:27px;height:27px;border:1px solid var(--gold);display:grid;place-items:center;font-family:'Playfair Display';font-size:13px;color:var(--gold)}.navLinks{display:flex;gap:25px}.navLinks a{font-size:9px;letter-spacing:.13em;text-transform:uppercase;color:#8f8b82;text-decoration:none}.navLinks a:hover{color:var(--gold2)}
.hero{width:min(1240px,calc(100% - 48px));margin:auto;min-height:610px;position:relative;display:flex;align-items:flex-end;padding:90px 0 70px;overflow:hidden}.hero:after{content:"P2";position:absolute;right:-25px;top:70px;font:900 300px/.75 'Bebas Neue';color:rgba(255,255,255,.018);letter-spacing:-.04em}.heroGrid{position:absolute;inset:0;background:linear-gradient(90deg,rgba(8,9,10,.98) 0%,rgba(8,9,10,.72) 48%,rgba(8,9,10,.98) 100%),radial-gradient(ellipse at 72% 45%,rgba(168,59,39,.18),transparent 32%);border-bottom:1px solid var(--line)}.heroContent{position:relative;z-index:1;max-width:950px}.eyebrow{display:flex;align-items:center;gap:12px;font-size:10px;font-weight:700;letter-spacing:.35em;color:var(--gold);text-transform:uppercase}.eyebrow:before{content:"";width:42px;height:1px;background:var(--gold)}.heroTitle{margin:20px 0 0;font-family:'Bebas Neue',sans-serif;font-size:clamp(100px,15vw,205px);line-height:.72;letter-spacing:.015em;text-transform:uppercase;color:#eee8dc;text-shadow:0 20px 70px #000}.heroTitle span{display:block;font-family:'Playfair Display',serif;font-style:italic;font-weight:900;font-size:.30em;letter-spacing:.02em;line-height:1.1;color:var(--gold2);margin:25px 0 0 9px;text-transform:none}.heroMeta{display:flex;gap:32px;margin-top:35px;color:#8d8980;font-size:10px;letter-spacing:.08em}.heroMeta b{display:block;color:#ddd8cd;font-size:11px;margin-top:5px}.heroRule{margin-top:35px;height:1px;width:150px;background:linear-gradient(90deg,var(--gold),transparent)}
.container{width:min(1120px,calc(100% - 48px));margin:auto}.headlineStats{display:grid;grid-template-columns:1.25fr 1fr 1fr;gap:1px;background:var(--line);border:1px solid var(--line);margin-top:-1px}.stat{background:linear-gradient(145deg,#151719,#0d0f11);min-height:154px;padding:25px 28px;position:relative;overflow:hidden}.stat:first-child{background:linear-gradient(145deg,#20170f,#0e1011)}.stat:after{content:"";position:absolute;width:120px;height:120px;border-radius:50%;right:-60px;bottom:-65px;background:rgba(212,168,92,.08)}.statLabel{font-size:8px;letter-spacing:.25em;text-transform:uppercase;color:#8c877d}.statValue{font-family:'Playfair Display',serif;font-weight:800;font-size:36px;letter-spacing:-.035em;margin-top:14px}.statValue small{font-family:'DM Sans';font-size:11px;color:var(--gold);letter-spacing:.1em}.statNote{font-size:8px;color:#55534e;margin-top:7px}
.quick{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:12px 0 90px}.quickCard{padding:19px;background:#0e1012;border:1px solid var(--line);position:relative}.quickCard:before{content:"";position:absolute;left:0;top:0;width:24px;height:2px;background:var(--gold)}.quickLabel{font-size:7px;letter-spacing:.2em;color:#77736a;text-transform:uppercase}.quickValue{font-family:'Playfair Display';font-size:20px;font-weight:800;margin-top:9px}.quickValue small{font:600 8px 'DM Sans';color:var(--gold)}
.section{padding:0 0 78px}.sectionHead{display:flex;align-items:flex-end;justify-content:space-between;border-bottom:1px solid var(--line);padding-bottom:17px;margin-bottom:18px}.kicker{font-size:8px;letter-spacing:.3em;text-transform:uppercase;color:var(--gold);font-weight:700}.section h2{font-family:'Playfair Display';font-size:28px;line-height:1;margin:8px 0 0;letter-spacing:-.02em}.sectionNo{font:400 50px/.8 'Bebas Neue';color:#34332f}
.langGrid{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}.lang{background:#101214;border:1px solid var(--line);padding:20px 17px;min-height:120px;transition:.25s}.lang:hover{transform:translateY(-4px);border-color:#685437}.langTop{display:flex;justify-content:space-between;font-size:9px}.langTag{font-size:6px;text-transform:uppercase;color:#69665e;letter-spacing:.12em}.langValue{font:800 24px 'Playfair Display';margin-top:29px}.langValue small{font:600 8px 'DM Sans';color:var(--gold)}
.tableWrap{overflow:auto;border:1px solid var(--line);background:#0d0f11}table{width:100%;border-collapse:collapse;min-width:650px}th{padding:12px 16px;text-align:right;border-bottom:1px solid var(--line);font-size:7px;letter-spacing:.18em;text-transform:uppercase;color:#6f6c65;font-weight:700}th:first-child{text-align:left}td{padding:15px 16px;text-align:right;border-bottom:1px solid #1b1d1f;font-size:10px;color:#aaa69e}td:first-child{text-align:left}td.name{color:#e0dbd0;font-weight:600}tbody tr:last-child td{border-bottom:0}tbody tr:last-child{background:rgba(212,168,92,.045)}tbody tr:last-child td{color:#e8dfd0;font-weight:700}
.opening{display:grid;grid-template-columns:1fr 1fr;gap:12px}.feature{background:linear-gradient(145deg,#18130e,#0d0f11);border:1px solid var(--line);padding:30px;min-height:245px;position:relative;overflow:hidden}.feature .big{font:800 74px/.9 'Playfair Display';margin-top:25px}.feature .big small{font:600 10px 'DM Sans';color:var(--gold)}.feature p{font-size:8px;color:#706d66;letter-spacing:.1em;text-transform:uppercase}
.dayGrid{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-bottom:16px}.day{border:1px solid var(--line);background:#0e1012;padding:18px;min-height:145px;position:relative}.dayNum{font-size:7px;letter-spacing:.2em;color:var(--gold)}.dayVal{font:800 23px 'Playfair Display';margin-top:24px}.dayVal small{font:600 8px 'DM Sans';color:var(--gold)}.bar{position:absolute;bottom:13px;left:18px;right:18px;height:3px;background:#1d1f20}.bar i{display:block;height:100%;background:linear-gradient(90deg,var(--gold),#6c4b24);width:var(--w)}
.final{margin:10px 0 0;border-top:1px solid var(--line);border-bottom:1px solid var(--line);padding:85px 0 95px;text-align:center;position:relative;overflow:hidden}.final:before{content:"LIFETIME";position:absolute;left:50%;top:10px;transform:translateX(-50%);font:900 150px/.8 'Bebas Neue';color:rgba(255,255,255,.018);white-space:nowrap}.finalKicker{position:relative;font-size:8px;letter-spacing:.35em;color:var(--gold);text-transform:uppercase}.finalTitle{position:relative;font:700 20px 'Playfair Display';margin-top:12px}.finalValue{position:relative;font:900 clamp(72px,12vw,145px)/.85 'Playfair Display';color:var(--gold2);letter-spacing:-.055em;margin-top:25px;text-shadow:0 20px 60px rgba(0,0,0,.8)}.finalValue small{font:600 12px 'DM Sans';letter-spacing:.15em;color:var(--gold)}
.note{margin:40px 0 0;padding:17px 20px;border-left:2px solid var(--gold);background:#101214;color:#77736a;font-size:8px;line-height:1.7}.note b{color:#bcb5a8}.footer{padding:28px 0 45px;text-align:center;font-size:7px;letter-spacing:.22em;color:#4d4b47;text-transform:uppercase}
@media(max-width:850px){.navLinks{display:none}.headlineStats{grid-template-columns:1fr}.quick{grid-template-columns:1fr 1fr}.langGrid{grid-template-columns:repeat(2,1fr)}.opening{grid-template-columns:1fr}.dayGrid{grid-template-columns:repeat(2,1fr)}.hero{min-height:510px}.heroTitle{font-size:clamp(88px,21vw,150px)}}
@media(max-width:520px){.navInner,.hero,.container{width:calc(100% - 28px)}.nav{height:58px}.hero{min-height:450px;padding-bottom:45px}.heroMeta{gap:18px;flex-wrap:wrap}.heroTitle span{font-size:.36em}.quick{grid-template-columns:1fr}.langGrid{grid-template-columns:1fr}.dayGrid{grid-template-columns:1fr 1fr}.stat{min-height:130px;padding:21px}.statValue{font-size:31px}.section{padding-bottom:58px}.section h2{font-size:23px}.final{padding:65px 0}.final:before{font-size:95px}}
`}</style>
  <nav className="nav"><div className="navInner"><div className="brand"><span className="brandMark">P2</span> BOX OFFICE ARCHIVE</div><div className="navLinks"><a href="#opening">Opening</a><a href="#territory">Territories</a><a href="#days">10 Days</a><a href="#overseas">Overseas</a><a href="#lifetime">Lifetime</a></div></div></nav>
  <header className="hero"><div className="heroGrid"/><div className="heroContent"><div className="eyebrow">Theatrical Performance</div><h1 className="heroTitle">PUSHPA 2<span>the rule</span></h1><div className="heroMeta"><div>BOX OFFICE COLLECTION<b>Worldwide Theatrical</b></div><div>TRACKING<b>Producer / Trade Figures</b></div><div>REPORT<b>India + Overseas</b></div></div><div className="heroRule"/></div></header>
  <div className="container">
   <div className="headlineStats"><div className="stat"><div className="statLabel">Worldwide Gross</div><div className="statValue"><Money>1,742.10</Money></div><div className="statNote">Collection</div></div><div className="stat"><div className="statLabel">India Gross</div><div className="statValue"><Money>1,742.10</Money></div><div className="statNote">Domestic theatrical</div></div><div className="stat"><div className="statLabel">Overseas Gross</div><div className="statValue"><Money>1,742.10</Money></div><div className="statNote">International theatrical</div></div></div>
   <div className="quick">{[["Opening Day","227"],["First Weekend","227"],["India Net","227"],["Highest Day","227"]].map(x=><div className="quickCard" key={x[0]}><div className="quickLabel">{x[0]}</div><div className="quickValue">{x[1]} <small>Cr</small></div></div>)}</div>
   <Section num="01" kicker="Language Wise" title="Collection"><div className="langGrid">{languages.map(x=><div className="lang" key={x[0]}><div className="langTop"><strong>{x[0]}</strong><span className="langTag">{x[1]}</span></div><div className="langValue">{x[2]} <small>Cr</small></div></div>)}</div></Section>
   <Section id="opening" num="02" kicker="Opening Day" title="Day 1 — Worldwide"><div className="opening"><div className="feature"><div className="kicker">Worldwide Opening</div><div className="big">294 <small>Cr</small></div><p>Day 1 worldwide gross</p></div><Table headers={["Market","Net","Gross","Share"]} rows={[["India","192","226","—"],["Overseas","—","68","—"],["Worldwide","—","294.00","—"]]}/></div></Section>
   <Section id="territory" num="03" kicker="India Market" title="Territory Wise"><Table headers={["Territory","Net","Gross"]} rows={territoryOpening}/></Section>
   <Section id="days" num="04" kicker="Opening Run" title="Day 01 — Day 10"><div className="dayGrid">{days.map((v,i)=><div className="day" key={i}><div className="dayNum">DAY {String(i+1).padStart(2,"0")}</div><div className="dayVal">{v.toFixed(2)} <small>Cr</small></div><div className="bar" style={{'--w':`${Math.max(8,v/294*100)}%`} as React.CSSProperties}><i/></div></div>)}</div><Table headers={["Day","India Net","India Gross","Overseas","Worldwide","Cumulative"]} rows={dayRows}/></Section>
   <Section num="05" kicker="Milestone" title="First Weekend"><div className="headlineStats"><div className="stat"><div className="statLabel">India Gross</div><div className="statValue">1,471.10 <small>Cr</small></div></div><div className="stat"><div className="statLabel">Overseas Gross</div><div className="statValue">1,471.10 <small>Cr</small></div></div><div className="stat"><div className="statLabel">Worldwide Gross</div><div className="statValue">1,471.10 <small>Cr</small></div></div></div></Section>
   <Section id="overseas" num="06" kicker="Global Market" title="Overseas Collection"><Table headers={["Market","Gross","Share"]} rows={overseas}/></Section>
   <Section id="lifetime" num="07" kicker="Final Theatrical Run" title="Lifetime Collection"><div className="headlineStats"><div className="stat"><div className="statLabel">India Net</div><div className="statValue">271.00 <small>Cr</small></div></div><div className="stat"><div className="statLabel">India Gross</div><div className="statValue">271.00 <small>Cr</small></div></div><div className="stat"><div className="statLabel">Overseas Gross</div><div className="statValue">271.00 <small>Cr</small></div></div></div><div style={{height:35}}/><div className="kicker">Final Breakdown</div><h2>Language Wise</h2><Table headers={["Language","India Net","India Gross","Share"]} rows={[["Telugu","341.48","—","—"],["Hindi","812.14","—","—"],["Tamil","58.56","—","—"],["Kannada","7.77","—","—"],["Malayalam","14.15","—","—"],["Other / Combined","—","—","—"],["India Total","1,234.10","1,471.10","—"]]}/><div style={{height:28}}/><div className="kicker">Final Breakdown</div><h2>Territory Wise</h2><Table headers={["Territory","Net","Gross"]} rows={[["Andhra Pradesh","—","117.90"],["Telangana","—","149.70"],["AP + Telangana","—","320.80"],["Karnataka","—","86.75"],["Tamil Nadu","—","96.85"],["Kerala","—","Included in TN + Kerala 96.85"],["Rest of India","—","809.35"],["India Total","1,234.10","1,471.10"]]}/><div style={{height:28}}/><div className="kicker">Final Breakdown</div><h2>Overseas Wise</h2><Table headers={["Market","Lifetime Gross","Share / Note"]} rows={overseas}/></Section>
   <div className="final"><div className="finalKicker">Worldwide Lifetime</div><div className="finalTitle">Pushpa 2: The Rule</div><div className="finalValue">1,871 <small>Cr</small></div></div>
   <div className="note"><b>Note:</b> All collection figures displayed on this page are in <b>Indian Rupees (INR)</b>. The ₹ symbol has intentionally been omitted from individual figures for a cleaner data presentation.</div>
   <footer className="footer">Pushpa 2 — Box Office Collection • Theatrical Performance Archive</footer>
  </div>
 </div>
}
